#pragma kernel UpdateDirections
#pragma kernel UpdatePositions

struct BoidModel
{
    float3 position;
    float3 direction;
};

RWStructuredBuffer<BoidModel> boids;
int nbThreadsPerGroups;

float dt;

/* ------------- BOID SETTINGS ------------- */
int nbBoids;
float speed;
float rotationSpeed;
int fieldOfVision;
float maneuverability;
int minDistance;
int rayonAround;
int maxAngleVertical;
float boundsWeight;
float cohesionWeight;
float alignmentWeight;
float separationWeight;

/* ------------- BOUNDS SETTINGS ------------- */
float width;
float height;
float depth;
float margin;
float3 center;

bool IsVisibleNeighbor(float3 boidDirection, float3 towardBoid2, float sqrDistance);
float3 LimitVerticalAngle(float3 boidDirection);
float3 ApplyForceToStayInBoundaries(float3 boidPosition);
float3 CalculateDirection(float3 boidDirection, 
    float3 boidPosition, 
    float3 separation, 
    float3 cohesion, 
    float3 alignment);

[numthreads(nbThreadsPerGroups, 1, 1)]
void UpdateDirections(uint id : SV_DispatchThreadID)
{
    if(id >= nbBoids)
        return;
    
    // 1 thread = 1 boid
    BoidModel boid = boids[id];
    
    uint nbVisibleNeighbors = 0;
    uint nbNeighborsAround = 0;
    
    float3 separation = float3(0, 0, 0);
    float3 alignment = float3(0, 0, 0);
    float3 cohesion = float3(0, 0, 0);
    
    float3 diff = float3(0, 0, 0);
    float3 centerOfMass = float3(0, 0, 0);
    float sqrDistance = 0.0;
    
    // Finds neighbors and calculates the new direction based on the 3 rules
    for(uint i = 0; i < nbBoids; i++)
    {
        if(i != id)
        {
            BoidModel otherBoid = boids[i];
            diff = boid.position - otherBoid.position;
 
            sqrDistance = dot(diff, diff);
            diff = normalize(diff);
            
            // separation
            if(sqrDistance > 0.0 && sqrDistance < minDistance * minDistance)
            {
                separation += diff / sqrDistance;
                nbNeighborsAround++;
            }
            // alignment and cohesion
            if(IsVisibleNeighbor(boid.direction, diff, sqrDistance))
            {
                alignment += otherBoid.direction;
                centerOfMass += otherBoid.position;
                nbVisibleNeighbors++;
            }
        }
    }
    
    // separation
    if(nbNeighborsAround > 0)
    {
        separation /= (float) nbNeighborsAround;
        separation = normalize(separation);
        separation = (separation - boid.direction) * separationWeight;
    }
    // alignment and cohesion
    if(nbVisibleNeighbors > 0)
    {
        alignment /= (float) nbVisibleNeighbors;
        alignment = normalize(alignment);
        alignment = (alignment - boid.direction) * alignmentWeight;
        
        // calculation of the average position of the neighbors (center of mass)
        centerOfMass /= (float) nbVisibleNeighbors; 
        // direction toward the center
        cohesion = (centerOfMass - boid.position);
        cohesion = normalize(cohesion);
        cohesion = (cohesion - boid.direction) * cohesionWeight;
    }
    
    boid.direction = CalculateDirection(boid.direction, boid.position, separation, cohesion, alignment);
    
    boids[id] = boid;
}

/* il faut faire ça après avoir calculé la nouvelle direction pour TOUS les boids, 
sinon on va se retrouver avec des boids qui vont se déplacer en fonction de la 
direction des autres boids qui ont déjà été mis à jour */
[numthreads(nbThreadsPerGroups, 1, 1)]
void UpdatePositions(uint id : SV_DispatchThreadID)
{
    if (id >= nbBoids)
        return;
    
    // 1 thread = 1 boid
    BoidModel boid = boids[id];
    boid.position += boid.direction * speed * dt;
    
    boids[id] = boid;
}

float3 CalculateDirection(float3 boidDirection, 
    float3 boidPosition, 
    float3 separation, 
    float3 cohesion, 
    float3 alignment)
{
    float3 directionCorrection = separation +
        cohesion +
        alignment + 
        ApplyForceToStayInBoundaries(boidPosition);

    float3 newDirection = boidDirection + directionCorrection;

    if(dot(newDirection, newDirection) > 0.0)
    {
        newDirection = normalize(newDirection);
        // interpolation between the current direction and the new direction based on maneuverability
        boidDirection = (1 - maneuverability) * boidDirection + maneuverability * newDirection;

        boidDirection = normalize(boidDirection);
        boidDirection = LimitVerticalAngle(boidDirection);
    }
    
    return boidDirection;
}

float3 ApplyForceToStayInBoundaries(float3 boidPosition)
{
    float3 v = float3(0, 0, 0);

    float minWidth = center.x - width / 2.0;
    float minHeight = center.y - height / 2.0;
    float minDepth = center.z - depth / 2.0;

    float maxWidth = center.x + width / 2.0;
    float maxHeight = center.y + height / 2.0;
    float maxDepth = center.z + depth / 2.0;

    // Width boundaries
    if (boidPosition.x > maxWidth - margin)
        v.x = -( (boidPosition.x - (maxWidth - margin)) / margin );

    else if (boidPosition.x < minWidth + margin)
        v.x = ( (minWidth + margin) - boidPosition.x ) / margin;

    // Height boundaries
    if (boidPosition.y > maxHeight - margin)
        v.y = -( (boidPosition.y - (maxHeight - margin)) / margin );

    else if (boidPosition.y < minHeight + margin)
        v.y = ( (minHeight + margin) - boidPosition.y ) / margin;

    // Depth boundaries
    if (boidPosition.z > maxDepth - margin)
        v.z = -( (boidPosition.z - (maxDepth - margin)) / margin );

    else if (boidPosition.z < minDepth + margin)
        v.z = ( (minDepth + margin) - boidPosition.z ) / margin;

    if (v != float3(0, 0, 0))
    {
        v = normalize(v);
        v *= boundsWeight;
    }

    return v;
}

float3 LimitVerticalAngle(float3 boidDirection) 
{
    // sin of the max vertical angle (convert to radian)
    float maxAngle = sin( radians(maxAngleVertical) );

    boidDirection.y = clamp(boidDirection.y, -maxAngle, maxAngle);

    return normalize(boidDirection);
}

// je dois m'assurer que boidDirection et towardBoid2 soient normalisés avant d'appeler cette fonction
// towardBoid2 => ok normarlisé
bool IsVisibleNeighbor(float3 boidDirection, float3 towardBoid2, float sqrDistance)
{
    // Check if boid2 is around boid1
    if (sqrDistance > rayonAround * rayonAround)
        return false;

    // Check if boid2 is within the field of vision
    // /!\ both vectors must be normalized 
    float cosAngle = dot(boidDirection, towardBoid2);
    
    // cos(angle) instead of angle to avoid calling arccos which is expensive
    // /!\  we compare cos, not angles themselves. 
    // angle < fieldOfVision / 2  <=> cos(angle) > cos(fieldOfVision / 2)
    // /!\ fieldOfVision is in degrees, so we convert it to radians
    return cosAngle > cos( radians(fieldOfVision / 2.0) );
}