#pragma kernel Update
#define NB_THREADS 256

struct BoidModel
{
    float3 position;
    float3 direction;
};

RWStructuredBuffer<BoidModel> boids;

float dt;

/* ------------- BOID SETTINGS ------------- */
int nbBoids;
float speed;
float rotationSpeed;
int fieldOfVision;
float maneuverability;
int minDistance;
int rayonAround;
int maxAngleVertical;
float boundsWeight;
float cohesionWeight;
float alignmentWeight;
float separationWeight;

/* ------------- BOUNDS SETTINGS ------------- */
float width;
float height;
float depth;
float margin;
float3 center;

bool IsVisibleNeighbor(BoidModel boid1, float3 towardBoid2, float sqrDistance);
float3 CalculateDirection(float3 boidDirection, float3 separation, float3 cohesion, float3 alignment);

[numthreads(NB_THREADS, 1, 1)]
void Update(uint id : SV_DispatchThreadID)
{
    if(id >= nbBoids)
        return;
    
    // 1 thread = 1 boid
    BoidModel boid = boids[id];
    
    uint nbVisibleNeighbors = 0;
    uint nbNeighborsAround = 0;
    
    float3 separation = float3(0, 0, 0);
    float3 alignment = float3(0, 0, 0);
    float3 cohesion = float3(0, 0, 0);
    
    float3 diff = float3(0, 0, 0);
    float3 centerOfMass = float3(0, 0, 0);
    float sqrDistance = 0f;
    
    // Finds neighbors and calculates the new direction based on the 3 rules
    for(uint i = 0; i < nbBoids; i++)
    {
        if(i != id)
        {
            BoidModel otherBoid = boids[i];
            diff = boid.position - otherBoid.position;
 
            sqrDistance = dot(diff, diff);
            diff = normalize(diff);
            
            // separation
            if(sqrDistance > 0f && sqrDistance < minDistance * minDistance)
            {
                separation += diff / sqrDistance;
                nbNeighborsAround++;
            }
            // alignment and cohesion
            if(IsVisibleNeighbor(boid, diff, sqrDistance))
            {
                alignment += otherBoid.direction;
                centerOfMass += otherBoid.position;
                nbVisibleNeighbors++;
            }
        }
    }
    
    // separation
    if(nbNeighborsAround > 0)
    {
        separation /= (float) nbNeighborsAround;
        separation = normalize(separation);
        separation = (separation - boid.direction) * separationWeight;
    }
    // alignment and cohesion
    if(nbVisibleNeighbors > 0)
    {
        alignment /= (float) nbVisibleNeighbors;
        alignment = normalize(alignment);
        alignment = (alignment - boid.direction) * alignmentWeight;
        
        // calculation of the average position of the neighbors (center of mass)
        centerOfMass /= (float) nbVisibleNeighbors; 
        // direction toward the center
        cohesion = (centerOfMass - boid.position);
        cohesion = normalize(cohesion);
        cohesion = (cohesion - boid.direction) * cohesionWeight;
    }
    
    boid.direction = CalculateDirection(boid.direction, separation, cohesion, alignment);
    
    /* il faut faire ça après avoir calculé la nouvelle direction pour TOUS les boids, 
    sinon on va se retrouver avec des boids qui vont se déplacer en fonction de la 
    direction des autres boids qui ont déjà été mis à jour */
    boid.position += boid.direction * speed * dt;
    boids[id] = boid;
}

float3 CalculateDirection(float3 boidDirection, float3 separation, float3 cohesion, float3 alignment)
{
    float3 directionCorrection = separation +
    cohesion +
    alignment;
    //+ ApplyForceToStayInBoundaries(boid);

    float3 newDirection = boidDirection + directionCorrection;

    if(dot(newDirection, newDirection) > 0f)
    {
        newDirection = normalize(newDirection);

        boidDirection = (1 - maneuverability) * boidDirection + maneuverability * newDirection;

        boidDirection = normalize(boidDirection);

        //boidDirection = LimitVerticalAngle(boidDirection);
    }
    
    return boidDirection;
}

// je dois m'assurer que boid1.direction et towardBoid2 soient normalisés avant d'appeler cette fonction
// towardBoid2 => ok normarlisé
bool IsVisibleNeighbor(BoidModel boid1, float3 towardBoid2, float sqrDistance)
{
    // Check if boid2 is around boid1
    if (sqrDistance > rayonAround * rayonAround)
        return false;

    // Check if boid2 is within the field of vision
    // /!\ both vectors must be normalized 
    float cosAngle = dot(boid1.direction, towardBoid2);
    
    // cos(angle) instead of angle to avoid calling arccos which is expensive
    // /!\  we compare cos, not angles themselves. 
    // angle < fieldOfVision / 2  <=> cos(angle) > cos(fieldOfVision / 2)
    // /!\ fieldOfVision is in degrees, so we convert it to radians
    return cosAngle > cos( radians(fieldOfVision / 2f) );
}